#!/bin/bash

# Output file name
output="autostart_programs.txt"

# Clear the output file if it exists
if [ -f "$output" ]; then
  rm "$output"
fi

# Write the header to the output file
echo "This is a list of programs that run automatically when booting a computer in a Linux Ubuntu environment." >> "$output"
echo "Generated by $(whoami) on $(date)" >> "$output"
echo "" >> "$output"

# Loop through the autostart directories and append the program names and descriptions to the output file
for dir in /etc/xdg/autostart ~/.config/autostart; do
  if [ -d "$dir" ]; then
    echo "📂 Programs in $dir:" >> "$output"
    for file in "$dir"/*.desktop; do
      name=$(grep -m 1 "^Name=" "$file" | cut -d "=" -f 2)
      comment=$(grep -m 1 "^Comment=" "$file" | cut -d "=" -f 2)
      echo "➡️ $name: $comment" >> "$output"
    done
    echo "" >> "$output"
  fi
done

# Display the output file with colors using tput command
tput setaf 3 # Set foreground color to yellow
echo "📂 Directories:" >> "$output"
tput sgr0 # Reset text attributes

# Print directory names with yellow color
echo "$(tput setaf 3)$(grep "📂" "$output")$(tput sgr0)" >> "$output"

# Print other lines with default color
grep -v "📂" "$output" >> "$output"

# Display the output file
cat "$output"

