#!/bin/bash

# output file name
output="autostart_programs.txt"

# clear the output file if it exists
if [ -f "$output" ]; then
  rm "$output"
fi

# write the header to the output file
echo "This is a list of programs that run automatically when booting a computer in a Linux Ubuntu environment." >> "$output"
echo "Generated by Bing on $(date)" >> "$output"
echo "" >> "$output"

# loop through the autostart directories and append the program names and descriptions to the output file
for dir in /etc/xdg/autostart ~/.config/autostart; do
  if [ -d "$dir" ]; then
    echo "📂 Programs in $dir:" >> "$output"
    for file in "$dir"/*.desktop; do
      name=$(grep -m 1 "^Name=" "$file" | cut -d "=" -f 2)
      comment=$(grep -m 1 "^Comment=" "$file" | cut -d "=" -f 2)
      echo "➡️ $name: $comment" >> "$output"
    done
    echo "" >> "$output"
  fi
done

# display the output file with colors using tput command
tput setaf 3 # set foreground color to yellow
cat "$output" | grep "📂" # print directory names with yellow color
tput sgr0 # reset text attributes
cat "$output" | grep -v "📂" # print other lines with default color


